#To define project-wide settings and change default behaviors
[pytest]
pythonpath = .
testpaths = tests

# Enable live logging
log_cli = true
log_cli_level = INFO

# Specifically for the HTML report and captured logs
log_html = true